### ISSUE TITLE
Brew install prefix issue

### ISSUE THREAD

**Issue by gdsmith** [derekstavis/plugin-nvm#4]
After installing nvm via brew and then adding the nvm plugin, when I try eg:

```
⋊> /V/M/p/aurelia nvm use current                                                                                                                                            
```

I get

```
nvm is not compatible with the npm config "prefix" option: currently set to "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.1.0"
Run `npm config delete prefix` or `nvm use --delete-prefix v5.1.0` to unset it.
```

Using the `--delete-prefix` does work, but I always need to use it or it fails. Any ideas how to fix it? Is there a better way to install nvm?

**Comment by derekstavis** [comment]
I haven't installed nvm through Homebrew. I recommend you using the [official installer](https://github.com/creationix/nvm#install-script).
