### ISSUE TITLE
Node not available on a new terminal

### ISSUE THREAD

**Issue by ghost** [derekstavis/plugin-nvm#6]
Whenever I open a new tab or a completely new terminal I always have to do

```
$ nvm use x.y.z
```

or else I will get:

> The program 'npm' is currently not installed. You can install it by typing:
> sudo apt-get install npm

I have just run `omf update` just to make sure that I had everything updated.

**Comment by derekstavis** [comment]
If you don't have a system-installed node (via `brew`, `apt`, `yum`) you need to alias a nvm-installed version to `system`.

**Comment by ghost** [comment]
Could you care to explain? How can I do that? doing a `nvm alias default x.y.z` isn't enough?

**Comment by derekstavis** [comment]
Please give a check if this solves the issue for you and report back.

**Comment by derekstavis** [comment]
Sure. Start a nested shell with `env OMF_IGNORE=nvm fish`, this will nest a fish session without this plugin active. Paste us the output of `type node`.

If the output is `type: Could not find “node”`, alias an installed node version to nvm's `default` node using `nvm alias default <node-version>`.

Unnest the shell with `exit`, you will be back to your previous session, then type `refresh` and check if you are good to go.

**Comment by ghost** [comment]
Yep that work, thanks a lot!
