### ISSUE TITLE
Doesn't work on FreeBSD 10.2-RELEASE  

### ISSUE THREAD

**Issue by joseluisq** [derekstavis/plugin-nvm#7]
``` sh
source: not found
nvm: not found
```

![image](https://cloud.githubusercontent.com/assets/1700322/12370441/1871d62c-bbdf-11e5-90fe-06e7e36c0f2f.png)

**Comment by derekstavis** [comment]
Could your please paste the output of `bash -c 'type source'`? What's your `bash` version?

**Comment by joseluisq** [comment]
I don't have `bash` I have [tcsh](https://www.freebsd.org/doc/en/articles/linux-users/shells.html) by default (`sh`)

``` sh
$ tcsh --version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-amd-FreeBSD) options wide,nls,dl,al,kan,sm,rh,color,filec
```

**Comment by derekstavis** [comment]
Hm, I think I wasn't prepared to this! Some questions:
1. Does `bash` points to `tcsh`?
2. If doesn't, what's `bash --version`?
3. Does `tcsh` have a `source` function/builtin? 
4. Have you ever used `nvm` in `tcsh`?

**Comment by joseluisq** [comment]
1. Fish to the default shell.
2. No, I haven't used (but I have used nvm on Linux OS)

**Comment by derekstavis** [comment]
You need to install bash. I have tested here and it works:

![screen shot 2016-01-17 at 10 56 15 pm](https://cloud.githubusercontent.com/assets/1611639/12381274/a0d9920e-bd6d-11e5-8b30-59b96d19de1d.png)

But nvm is sad anyway on FreeBSD :(

![screen shot 2016-01-17 at 10 58 22 pm](https://cloud.githubusercontent.com/assets/1611639/12381285/e49b8678-bd6d-11e5-91ec-4083f22a56ea.png)

**Comment by joseluisq** [comment]
With `bash` by default shell `nvm` works fine but...
For this issue https://github.com/nodejs/node/issues/3716
So that I had decided to install Node from official package :smile: 

``` sh
$ sudo pkg install node npm
```

I will close this issue anyway.
Thanks.
